### ISSUE TITLE
standalone VPN clients page is not indexed

### ISSUE THREAD

**Issue by MHBauer** [IBM-Bluemix-Docs/iaas-vpn#14]
https://console.bluemix.net/docs/infrastructure/iaas-vpn/standalone-vpn-clients.html
https://github.com/IBM-Bluemix-Docs/iaas-vpn/blob/master/standalone-vpn-clients.md

This page has no sidebar, and is not linked from anywhere.

**Comment by sheltons** [comment]
Hi, Morgan.
Because this page can go out of date so easily with such specific information, we decided to keep this page essentially private, thus there is no sidebar and a person has to know the exact URL to reach it. It is working as designed. If it requires updating, please submit a pull request with the correct information, and we will update it accordingly.
